# Generated by Django 5.0 on 2025-12-23 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='annual_income',
        ),
        migrations.RemoveField(
            model_name='student',
            name='bus_route_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='marksheet_scan',
        ),
        migrations.RemoveField(
            model_name='student',
            name='permanent_address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='previous_school',
        ),
        migrations.RemoveField(
            model_name='student',
            name='transport_required',
        ),
        migrations.RemoveField(
            model_name='student',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='student',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.academicsession'),
        ),
        migrations.AlterField(
            model_name='academicsession',
            name='year',
            field=models.CharField(help_text='e.g., 2024-2025', max_length=9),
        ),
        migrations.AlterField(
            model_name='student',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='primary_mobile',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='secondary_mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
