# Generated by Django 5.0 on 2025-12-27 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='affiliation',
            field=models.CharField(blank=True, help_text='Ex: CBSE, ICSE, State Board', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='affiliation_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='code',
            field=models.CharField(default='SCH-001', help_text='Ex: SCH-101', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institution',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='institutes/logos/'),
        ),
        migrations.AddField(
            model_name='institution',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='principal_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='institutes/signatures/'),
        ),
        migrations.AddField(
            model_name='institution',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='type',
            field=models.CharField(choices=[('School', 'School'), ('College', 'College'), ('Coaching', 'Coaching'), ('University', 'University')], default='School', max_length=50),
        ),
        migrations.AddField(
            model_name='institution',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
