# Generated by Django 5.1.5 on 2026-01-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_date',
            field=models.DateTimeField(blank=True, help_text='Exam ki date aur time', null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='is_notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
